services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - ../docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090/9090
    networks:
      - astro_default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - conf/.credentials.conf
    ports:
      - "3000:3000"  
    depends_on:
      - prometheus  
    networks:
      - astro_default
    volumes:
      - grafana-storage:/var/lib/grafana  

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      - astro_default


networks:
  astro_default:
    driver: bridge

volumes:
  grafana-storage: 